### ISSUE TITLE
Improve handling of wand.exceptions.CorruptImageError in imageresize.py

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-bot#1067]
An example today from ingesting eLife article `50469` included a `.tif` file which resulted in an exception when attempting to resize the image to `.jpg`. An example stack trace message in the `worker.log`:

```
2020-03-30T12:08:35Z ERROR worker_8130 error resizing image elife-50469-fig5-v2
Traceback (most recent call last):
  File "/opt/elife-bot/provider/imageresize.py", line 39, in resize
    image.save(file=image_buffer)
  File "/opt/elife-bot/venv/lib/python3.5/site-packages/wand/image.py", line 5042, in save
    file.write(self.make_blob())
  File "/opt/elife-bot/venv/lib/python3.5/site-packages/wand/image.py", line 4921, in make_blob
    self.raise_exception()
  File "/opt/elife-bot/venv/lib/python3.5/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.CorruptImageError: Insufficient memory (case 4) `' @ error/jpeg.c/JPEGErrorHandler/322
2020-03-30T12:08:35Z ERROR worker_8130 An error occurred during Convert Images To JPG
```

The longer lasting effect seemed to be a large amount of virtual memory was tied up with the Python worker process that tried to resize it, reaching 1.7Gb used.

I think we can make a small improvement to handle this particular exception

- [x] In `provider/imageresize.py`, if unable to `image.save()` the resized image due to `wand.exceptions.CorruptImageError` then log the exception and destroy the image to free up memory usage

**Comment by gnott** [comment]
Re issue https://github.com/elifesciences/issues/issues/5516
