### ISSUE TITLE
Handle exceptions raised in activity_FTPArticle due to FTP connections

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-bot#680]
FTP transfers can fail for a number of reasons, initially due to an inability to connect, later the connection may be dropped, or a timeout may be reached due to a slow transfer speed or a very large file.

Recently, how these exceptions are handled can cause problems of retrying to transfer files or connect multiple times to the same FTP server, and the monitoring service sends an alert.

The simplest logic could be if any exception is raised as part of the FTP transfer, then return ``ACTIVITY_PERMANENT_FAILURE`` from the activity, which will result in the workflow to be terminated and not tried again.

A more recent logic was added to https://github.com/elifesciences/elife-bot/blob/develop/activity/activity_PubmedArticleDeposit.py#L278 where the ``ftp_files_to_endpoint()`` function wraps the logic with exception handling, and it uses the functions from the ftp provider to connect and transfer files. I propose to following a similar refactoring for the ``FTPArticle`` activity, so any exception will result in the workflow to be terminated.

I'm not sure what to do to notify someone when a file fails to transfer, because it will not try to send it again.

Some common errors in the logs I will place below in the next comment, which we want to handle better.

**Comment by gnott** [comment]
Additional recently observed in the `worker.log`

```
Traceback (most recent call last):
  File "/opt/elife-bot/activity/activity_FTPArticle.py", line 116, in do_activity
    self.ftp_to_endpoint(zipfiles, passive=True)
  File "/opt/elife-bot/activity/activity_FTPArticle.py", line 434, in ftp_to_endpoint
    self.ftp_upload(ftp, uploadfile)
  File "/opt/elife-bot/activity/activity_FTPArticle.py", line 397, in ftp_upload
    ftp.storbinary("STOR " + uploadname, open(file, "rb"), 1024)
  File "/usr/lib/python3.6/ftplib.py", line 504, in storbinary
    with self.transfercmd(cmd, rest) as conn:
  File "/usr/lib/python3.6/ftplib.py", line 399, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/usr/lib/python3.6/ftplib.py", line 361, in ntransfercmd
    source_address=self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
```

```
Traceback (most recent call last):
  File "/opt/elife-bot/activity/activity_FTPArticle.py", line 118, in do_activity
    self.ftp_to_endpoint(zipfiles, passive=True)
  File "/opt/elife-bot/activity/activity_FTPArticle.py", line 434, in ftp_to_endpoint
    self.ftp_upload(ftp, uploadfile)
  File "/opt/elife-bot/activity/activity_FTPArticle.py", line 397, in ftp_upload
    ftp.storbinary("STOR " + uploadname, open(file, "rb"), 1024)
  File "/usr/lib/python3.6/ftplib.py", line 504, in storbinary
    with self.transfercmd(cmd, rest) as conn:
  File "/usr/lib/python3.6/ftplib.py", line 399, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/usr/lib/python3.6/ftplib.py", line 365, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "/usr/lib/python3.6/ftplib.py", line 273, in sendcmd
    return self.getresp()
  File "/usr/lib/python3.6/ftplib.py", line 246, in getresp
    raise error_perm(resp)
ftplib.error_perm: 550 elife-09-53683.zip: Cannot create file.
```

**Comment by gnott** [comment]
Many of these exceptions were recently improved in `FTPArticle` and the `ftp.py` provider, related PRs
- https://github.com/elifesciences/elife-bot/pull/1178
- https://github.com/elifesciences/elife-bot/pull/1180
- https://github.com/elifesciences/elife-bot/pull/1183

More refactoring opportunities remain, but for `FTPArticle` and FTP exceptions we can consider this issue closed.
